#!/bin/sh
SFE_HOME="${SFE_HOME:-/usr/lib/sfe}"
SFE_SYSTEM_PYTHON="${SFE_SYSTEM_PYTHON:-/usr/bin/python3}"
SFE_BUNDLED_PYTHON="${SFE_BUNDLED_PYTHON:-$SFE_HOME/python/bin/python3}"
SFE_NATIVE_LIB="$SFE_HOME/python/lib/native"
SFE_TERMINFO="$SFE_HOME/python/share/terminfo"
SFE_SELECTED_PYTHON="$SFE_SYSTEM_PYTHON"
SFE_USES_BUNDLED_PYTHON=0

if [ "${SFE_PREFER_BUNDLED_PYTHON:-0}" = "1" ] || [ ! -x "$SFE_SYSTEM_PYTHON" ]; then
    SFE_SELECTED_PYTHON="$SFE_BUNDLED_PYTHON"
    SFE_USES_BUNDLED_PYTHON=1
fi

if [ "$SFE_USES_BUNDLED_PYTHON" = "1" ] && [ -d "$SFE_NATIVE_LIB" ]; then
    if [ -n "${LD_LIBRARY_PATH:-}" ]; then
        export LD_LIBRARY_PATH="$SFE_NATIVE_LIB:$LD_LIBRARY_PATH"
    else
        export LD_LIBRARY_PATH="$SFE_NATIVE_LIB"
    fi
fi

if [ -d "$SFE_TERMINFO" ]; then
    if [ -n "${TERMINFO_DIRS:-}" ]; then
        export TERMINFO_DIRS="$SFE_TERMINFO:$TERMINFO_DIRS"
    else
        export TERMINFO_DIRS="$SFE_TERMINFO:/usr/share/terminfo:/lib/terminfo"
    fi
fi

exec "$SFE_SELECTED_PYTHON" -B -S "$SFE_HOME/sfe.py" "$@"
